# Generated by Django 5.1.1 on 2024-10-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('lotacao', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(max_length=3)),
                ('plano_saude', models.CharField(max_length=100)),
            ],
        ),
    ]
