# Generated by Django 5.1.1 on 2024-10-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0002_contatoemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('acidente', 'Acidente'), ('incendio', 'Incêndio'), ('emergencia_medica', 'Emergência Médica')], max_length=50)),
            ],
        ),
    ]
