# Generated by Django 5.1.1 on 2024-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0003_eventocritico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
