# Generated by Django 5.1.1 on 2024-10-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0004_lotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('lotacao', models.CharField(max_length=100)),
                ('tipo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=50)),
                ('plano_saude', models.CharField(max_length=100)),
                ('numero_plasau', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='contatoemergencia',
            name='cadastro',
        ),
        migrations.DeleteModel(
            name='EventoCritico',
        ),
        migrations.DeleteModel(
            name='Lotacao',
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='ContatoEmergencia',
        ),
    ]
