# Generated by Django 5.1.1 on 2024-10-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0007_local_rename_email_contatoemergencia_email_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoemergencia',
            name='celular_contato',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='local',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='local',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='local',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
