# Generated by Django 5.1.1 on 2024-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0008_alter_contatoemergencia_celular_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='complemento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='local',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
