# Generated by Django 5.1.1 on 2024-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pevams', '0010_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='forma_entrada',
            field=models.CharField(choices=[('porta aberta', 'porta aberta'), ('necessita regulação', 'necessita regulação')], default='porta aberta', max_length=50),
            preserve_default=False,
        ),
    ]
